In [2]:
import numpy as np
import pandas as pd

In [7]:
A = np.array([1, 2, 3, 4, 5, 6])
B = np.array([6, 7, 8, 9, 10, 11])
vertical = np.vstack([A, B])
horizontal = np.hstack([A, B])
print(vertical)
print(horizontal)

[[ 1  2  3  4  5  6]
 [ 6  7  8  9 10 11]]
[ 1  2  3  4  5  6  6  7  8  9 10 11]


In [8]:
print(np.intersect1d(A, B))

[6]


In [16]:
print(A[np.where((A > 5) & (A < 10))])

[6]


In [17]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)])

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [18]:
url = 'https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'
df = pd.read_csv(url)
print(df.iloc[::20, [0, 1, 2]])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [19]:
min_mean = df['Min.Price'].mean()
max_mean = df['Max.Price'].mean()
df['Min.Price'].fillna(min_mean, inplace=True)
df['Max.Price'].fillna(max_mean, inplace=True)

In [20]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
sums = df.sum(axis=1)
print(df[sums > 100])

     0   1   2   3
3   35  38  11  19
4   38  20  31  21
5   33  23  32  31
7   18  35  26  33
9   29  22  28  31
12  34  28  27  26
13  30  32  28  19
14  27  30  22  29
